weMail/wemail

- includes/Core/Campaign/Editor.php
- includes/Core/Customizer/ContentTypes.php
Here we can add countdown timer on email builder.
> Added ability to add countdown timer on builder Fixed #10

- includes/Rest/Auth.php
- includes/Rest/Users.php
- Site Registration
- Add new team member
- Update team member role
> Fixes null response

- includes/Core/Sync/Subscriber/Erp/Erp.php
- includes/Core/Sync/Subscriber/Erp/Hooks.php
- includes/Core/Sync/Subscriber/Wp/Hooks.php
- includes/Core/Sync/Subscriber/Wp/Wp.php
- includes/Rest/ERP.php
- includes/functions.php
- Added `/crm/contacts/(?P<id>[\d]+)` REST endpoint
> Refactor ERP and WP REST and SYNC

- includes/Core/Mail/MailerHelper.php
- includes/Core/Mail/WeMailMailer54.php
- includes/Core/Mail/WeMailMailer55.php
Convert `phpmailer` file attachment array to file urls array using `wp_get_attachment_url()` function
> Format email attachments on Transactional email

- includes/Core/Campaign/Editor.php
- includes/Core/Customizer/ContentTypes.php
> Added Giphy block for email builder

- includes/Core/Mail/MailerHelper.php
- includes/Core/Mail/WeMailMailer54.php
- includes/Core/Mail/WeMailMailer55.php
- Also, Send bcc and cc addresses
fixes #161
> Send reply to addresses to weMail on sending transactional email

- includes/Core/Form/Form.php
- includes/Core/Form/Integrations/Hooks.php
- includes/Core/Form/Integrations/PopupBuilder.php
related to https://github.com/weMail/wemail/issues/175
> popup builder integration

- includes/Core/Help/Services/PluginsInfo.php
- includes/Core/Help/Services/SystemService.php
- includes/Core/Help/Services/WordpressInfo.php
- includes/Core/Help/SystemInfo.php
debug log file location, upload directory, web port, chi version information issue fix
> system info issue fix

- includes/FrontEnd/FrontEnd.php
Also, fixed specific page show issue
> Added except pages option on form opt-in

- includes/Core/User/Integrations/WpUser.php
> Hotfix - weMail teams issue - Develop

- includes/Admin/Elementor/FormAction.php
- includes/functions.php
> Added elementor form integration

- includes/Admin/Scripts.php
- includes/FrontEnd/Scripts.php
- includes/WeMail.php
- includes/functions.php
- Also remove `SCRIPT_DEBUG` since we are using Hot module replacement.
> Added ability to configure hmr host url on Plugin

- includes/Admin/Scripts.php
Added here the site title in the localized data.
> Localized site title

- includes/Core/Ecommerce/Platforms/EDD.php
- includes/Rest/Ecommerce/Ecommerce.php
- includes/Rest/Resources/Ecommerce/EDD/OrderItemResource.php
- includes/Rest/Resources/Ecommerce/EDD/ProductResource.php
- includes/Rest/Resources/Ecommerce/WooCommerce/OrderItemResource.php
- Added categories on product
- use gmdate()
- fixed product id on order item
> Fixed issues ecommerce features

- includes/Core/Ecommerce/Ecommerce.php
- includes/Core/Ecommerce/Platforms/EDD.php
- includes/Core/Ecommerce/Platforms/WooCommerce.php
- includes/Core/Sync/Ecommerce/RevenueTrack.php
- includes/Rest/Resources/Ecommerce/EDD/OrderItemResource.php
- includes/Rest/Resources/Ecommerce/EDD/OrderResource.php
- includes/Rest/Resources/Ecommerce/EDD/OrderResourceV3.php
- includes/Rest/Resources/Ecommerce/EDD/ProductResource.php
- includes/Rest/Resources/Ecommerce/WooCommerce/CategoryResource.php
- includes/Rest/Resources/Ecommerce/WooCommerce/OrderItemResource.php
- includes/Rest/Resources/Ecommerce/WooCommerce/OrderResource.php
- includes/Rest/Resources/Ecommerce/WooCommerce/ProductResource.php
- includes/Rest/Resources/JsonResource.php
- Support EDD version 3
- Enhanced e-commerce API
> Enhance ecommerce API

- includes/Core/SuppressionLists/Menu.php
Issue - https://github.com/weMail/wemail-api/issues/638
Backend - https://github.com/weMail/wemail-api/pull/739
Frontend - https://github.com/weMail/wemail-cdn/pull/363
> Suppression list menu.

- includes/Rest/Help/Help.php
Fixed the rest permission issue. This will fix the [client issue](https://wedevs.slack.com/archives/G69HSF5HB/p1699705478056819)
> Fixed the rest permission issue. 

- includes/Rest/Users.php
Depended on [CDN](https://github.com/weMail/wemail-cdn/pull/404)
> Refactor team delete and update and Fixed team feature

- composer.json
- composer.lock
Resolved #https://github.com/weMail/wemail-api/issues/1025
> Fixed translation in wp 6.7.*

- includes/Core/Api/Api.php
- includes/Core/Auth/Auth.php
- includes/Core/User/User.php
- includes/Rest/Auth.php
After creating a Brand from the WP site or weMail-app, the client can connect a WP site with the brand
> site connection with the already-created brand
